name: Build and Run ConsumerApp

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '6.x'

      - name: Configure GitHub Package Source
        run: dotnet nuget add source "https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json" --name "github" --username "${{ github.repository_owner }}" --password "${{ secrets.GH_NUGET_TOKEN }}" --store-password-in-clear-text

      - name: Restore packages
        run: dotnet restore ConsumerApp/ConsumerApp.csproj

      - name: Build
        run: dotnet build ConsumerApp/ConsumerApp.csproj --configuration Release

      - name: Run
        run: dotnet run --project ConsumerApp/ConsumerApp.csproj
